### ISSUE TITLE
Get rid of the number in the end of path for getting link of each episode 

### ISSUE THREAD

**Issue by vucuong12** [ayhankuru/tv-subs#1]
I think it's better if you can edit the function to get the download link of each episode such that user dont need to know the number in the end of the path, for example:

tvsubs.subtitle({path:"/subtitles/new-girl-season-4-episode-13-english-291"}).then(function(data){
    console.log(data);
}).catch(function(err){
 
console.log(err);
 
});

-> it will be better if you can get rid of "291" in the path path:"/subtitles/new-girl-season-4-episode-13-english-291 because how can user know that number ?

**Comment by ayhankuru** [comment]
I look at this issue thanks :wink:

**Comment by vucuong12** [comment]
Hope you can fix it soon :). It will be very helpful. Thks in advance :)

**Comment by ayhankuru** [comment]
@vucuong12  Does this help you [#L75]( https://github.com/ayhankuru/tv-subs/blob/dev/lib/util.js#L75)

**Comment by vucuong12** [comment]
@ayhankuru thank you so much for your quick help.  However, after cloning dev branch, I cannot run  both files: example/chain.js and example/index.js. Then:

1. The first error i got is:
D:\project\tv-subs\lib\index.js:3
let got = require('got');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\project\tv-subs\example\index.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

-> I think it is because of using "let", so I change all "let" to "var" -> this error didn't appear again, but I still got another error as following:

2. Second error:
In some lines of code, you use ` instead of ' in your code (for example: in file lib/index.js, line 22: return got(url.resolve(apiurl, `/a_mov.php?reqmov=${query}`)).then(function (res) {   )

-> I change all ` to ', but I still got errors as following

3. The third error:
- I ran the file example/chain.js, and the result was:

[TypeError: Cannot read property 'value' of undefined]

- I ran the file example/index.js, and the result was (just give a part of it because it is too long):

[]
{ [HTTPError: Response code 404 (Not Found)]
  message: 'Response code 404 (Not Found)',
  code: undefined,
  host: 'www.tv-subs.com',
  hostname: 'www.tv-subs.com',
  method: 'GET',
  path: '/tv/$%7Bpath%7D',
  statusCode: 404,
  statusMessage: 'Not Found',
  response:
   { _readableState:
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
    ...

-> Here, I have no idea what to do next to fix it. Hope you can take a look at this. Thank you :)

**Comment by ayhankuru** [comment]
@vucuong12  1. This code``iojs`` executable es6
send me test code in gist url :)

**Comment by ayhankuru** [comment]
also readme.md not change, method values, checkout test, and example file

**Comment by vucuong12** [comment]
Sorry I actually don't know iojs executable es6.

I just modified only 2 files (lib/index.js and lib/util.js) here: https://gist.github.com/vucuong12/c194ad2b366469b0a7b2

Can you make it work without iojs? sorry about this too much demand.

**Comment by ayhankuru** [comment]
@vucuong12 you are test code need , ı am checkout eror

**Comment by ayhankuru** [comment]
@vucuong12 thanks, I am checkout this code

**Comment by vucuong12** [comment]
This API will be very great because now in the internet, there is no good API for TV subtitles. I tried opensubtitle API but they have a lot of limitation.

**Comment by ayhankuru** [comment]
@vucuong12 new version I published,

checkout example code and readme md


```
var tvsubs = require('tv-subs');

tvsubs.search('True Detective') // one argument  and string
.then(function (data) {
	console.log(data);
}).catch(function (err) {
	console.log(err);
});

```
